{
 "title": "sxbill",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "tg", "label": "trunk group number", "query": "118" },
   { "name": "timeInterval", "label": "time Interval", "query": "1h, 1d" }
  ]
 },
 "panels": [
  {
   "title": "Eralangs delta FromTgSec + delta FromTgSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Erlang" }
   ],
   "targets": [
    {
     "expr": "(delta(FromTgSec{tg=\"$tg\"}[$timeInterval])/60/60) + (delta(FromTgSec{tg=\"$tg\"}[$timeInterval])/60/60)",
     "legendFormat": "delta FromTgSec + delta FromTgSec"
    }
   ]
  },
  {
   "title": "rate Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ToTgNormCount{tg=\"$tg\"}[1h])",
     "legendFormat": "ToTgNormCount"
    },
    {
     "expr": "0 - rate(ToTgFailCount{tg=\"$tg\"}[1h])",
     "legendFormat": "ToTgFailCount"
    }
   ]
  },
  {
   "title": "Erlangs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(FromTgSec{tg=\"$tg\"}[$timeInterval])/60/60",
     "legendFormat": "FromTgSec/60/60"
    },
    {
     "expr": "0 - delta(ToTgSec{tg=\"$tg\"}[$timeInterval])/60/60",
     "legendFormat": "ToTgSec/60/60"
    }
   ]
  },
  {
   "title": " $tg Asr ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "FromTgNormCount{tg=\"$tg\"} * 100 / (FromTgFailCount{tg=\"$tg\"} + FromTgNormCount{tg=\"$tg\"}) ",
     "legendFormat": "From Tg $tg ASR"
    },
    {
     "expr": "ToTgNormCount{tg=\"$tg\"} * 100 / (ToTgNormCount{tg=\"$tg\"} + ToTgFailCount{tg=\"$tg\"})",
     "legendFormat": "To Tg $tg ASR"
    }
   ]
  },
  {
   "title": "delta TgSec $tg per $timeInterval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(FromTgSec{tg=\"$tg\"}[$timeInterval])/60",
     "legendFormat": "delta FromTgSec $tg"
    },
    {
     "expr": "0 - delta(ToTgSec{tg=\"$tg\"}[$timeInterval])/60",
     "legendFormat": "delta ToTgSec $tg"
    }
   ]
  },
  {
   "title": "FailCount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(FromTgFailCount{tg=\"$tg\"}[$timeInterval])",
     "legendFormat": "FromTgFailCount"
    },
    {
     "expr": "0 - delta(ToTgFailCount{tg=\"$tg\"}[$timeInterval])",
     "legendFormat": "ToTgFailCount"
    }
   ]
  },
  {
   "title": "Delta TgNormCount per $timeInterval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(FromTgNormCount{tg=\"$tg\"}[$timeInterval])",
     "legendFormat": "FromTgNormCount"
    },
    {
     "expr": "0 - delta(ToTgNormCount{tg=\"$tg\"}[$timeInterval])",
     "legendFormat": "ToTgNormCount"
    }
   ]
  },
  {
   "title": "To tg count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(ToTgNormCount{tg=\"$tg\"}[$timeInterval])",
     "legendFormat": "ToTgNormCount"
    },
    {
     "expr": "0-delta(ToTgFailCount{tg=\"$tg\"}[$timeInterval])",
     "legendFormat": "ToTgFailCount"
    }
   ]
  },
  {
   "title": "delta FromTg $tg Count per $timeInterval",
   "type": "graph",
   "description": "количество в час",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(FromTgNormCount{tg=\"$tg\"}[$timeInterval])",
     "legendFormat": "delta FromTgNormCount $tg "
    },
    {
     "expr": "0 - delta(FromTgFailCount{tg=\"$tg\"}[$timeInterval])",
     "legendFormat": "delta FromTgFailCount $tg "
    }
   ]
  }
 ]
}