{
 "title": "sxbill total",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "timeInterval", "query": "1h, 1d" }
  ]
 },
 "panels": [
  {
   "title": "topk(4, delta(FromTgSec[$timeInterval]))",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(4, delta(FromTgSec[$timeInterval]))",
     "legendFormat": "{{tg}}"
    }
   ]
  },
  {
   "title": "topk(4, rate(FromTgSec[$timeInterval]))",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(4, delta(FromTgSec[$timeInterval]))",
     "legendFormat": "tg={{tg}}"
    }
   ]
  },
  {
   "title": "topk(4, delta(ToTgSec[$timeInterval]))",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(4, delta(ToTgSec[$timeInterval]))",
     "legendFormat": "{{tg}}"
    }
   ]
  },
  {
   "title": "topk(3, delta(FromTgFailCount[$timeInterval]))",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, delta(FromTgFailCount[$timeInterval]))",
     "legendFormat": "tg={{tg}}"
    }
   ]
  },
  {
   "title": "topk(3, rate(FromTgNormCount[$timeInterval]))",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, rate(FromTgNormCount[$timeInterval]))",
     "legendFormat": "{{tg}}"
    }
   ]
  },
  {
   "title": "delta(TotalMinutes[$timeInterval])",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(TotalMinutes[$timeInterval])",
     "legendFormat": "TotalMinutes"
    }
   ]
  },
  {
   "title": "delta Calls count $timeInterval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(LocalNormCount[$timeInterval])",
     "legendFormat": "LocalNormCount"
    },
    {
     "expr": "0 - delta(LocalFailCount[$timeInterval])",
     "legendFormat": "LocalFailCount"
    },
    {
     "expr": "delta(NatNormCount[$timeInterval])",
     "legendFormat": "NatNormCount"
    },
    {
     "expr": "0 - delta(NatFailCount[$timeInterval])",
     "legendFormat": "NatFailCount"
    }
   ]
  },
  {
   "title": "Total Cdr",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(TotalNormCdr[$timeInterval])",
     "legendFormat": "TotalNormCdr"
    },
    {
     "expr": "0 - delta(TotalFailCdr[$timeInterval])",
     "legendFormat": "TotalFailCdr"
    }
   ]
  },
  {
   "title": "go_memstats_heap_sys_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_sys_bytes{instance=\"10.100.100.103:8080\", job=\"sxbill\"}"
    }
   ]
  }
 ]
}